tls:
  certificates:
    - certFile: /certs/whamarket.dev.crt
      keyFile: /certs/whamarket.dev.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/whamarket.dev.crt
        keyFile: /certs/whamarket.dev.key
